### ISSUE TITLE
PC Gamer March 1997 fails to mount properly

### ISSUE THREAD

**Issue by HeroponRikiBestest** [cdemu/cdemu#19]
Using a redump verified image (http://redump.org/disc/57778/) the disc fails to mount properly. If I try and mount it with CDEMU, it mounts as `1997-01-02-12-00-03-` with nothing inside of it.

Tested on CDEMU 3.2.5 on Linux Mint 20 Cinnamon

**Comment by rokm** [comment]
I cannot reproduce this.

The image (also verified against redump) mounts just fine on Fedora 35 with latest CDEmu release, as well as in a VM with Mint 20 Cinnamon and CDEmu 3.2.5. Both mount the disc as "619 MB Volume" (and Nemo file browser on Mint does indeed show `1997-01-02-12-00-03-` in title bar), but that's because the disc does not have a volume ID set. 

At any rate, CDEmu does not deal with filesystems itself, so whatever issue you're having, I doubt it is a CDEmu bug.

**Comment by HeroponRikiBestest** [comment]
I can confirm it works for me now.
