### ISSUE TITLE
Daemon refuses to load, complains of permissions.

### ISSUE THREAD

**Issue by lavadrop** [cdemu/cdemu#28]
I installed cdemu cdemu-daemon gcdemu and vhba-kmp-default from the openSUSE Tumbleweed repositories.
Right off the bat, it's missing the udev rules and the vhba conf file. No problem those can be generated.
After creating them as suggested in this openSUSE forum post from 2014 ( https://forums.opensuse.org/t/cdemu-how-do-i/99781/4 ) the daemon still refuses to load. 
Yes, I am part of the "users" group.

This is the error description:

```
Starting CDEmu daemon with following parameters:
 - config file: (null) (exists: 0)
 - num devices: 1
 - control device: /dev/vhba_ctl
 - audio driver: null
 - bus type: session
 - default CDEmu debug mask: 0x0
 - default libMirage debug mask: 0x0

Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)cdemu0: Kernel I/O: failed to open control device /dev/vhba_ctl: Permission denied!
cdemu: Daemon: failed to start device #0!
cdemu: Daemon: failed to create device!
Daemon initialization and start failed!

```
Any ideas why it fails?

**Comment by rokm** [comment]
> cdemu0: Kernel I/O: failed to open control device /dev/vhba_ctl: Permission denied!

Because your user has insufficient permissions to open the control file?

What is the output of `ls -l /dev/vhba_ctl`?

**Comment by lavadrop** [comment]
`crw------- 1 root root 10, 170 jan 14 12:28 /dev/vhba_ctl`

**Comment by rokm** [comment]
> `crw------- 1 root root 10, 170 jan 14 12:28 /dev/vhba_ctl`

So that's your problem - the control device is accessible only to root. So your udev rule from 2014 (if it is even being loaded and activated) is not doing its job.

This is distribution- and packaging-specific, so take it up with the source of your packages - i.e., why they do not provide udev rules, and by what mechanism the user should gain access to control device. 

FWIW, the Ubuntu and Fedora packages that I provide both include udev rule that sets `uaccess` tag (i.e., `KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="uaccess"`).

**Comment by lavadrop** [comment]
Thanks for pointing out the issue, I'll contact someone at the openSUSE forums.

**Comment by theMarix** [comment]
For anybody running into this like myself: The problem is not about group membership and the mechanism with the `uaccess` tag is actually the proper thing to do. However, currently on openSUSE there is a small issue with the package as the module is only loaded on demand, and until that point the udev-rule that SUSE ships is not evaluated. That's why you have the permissions only showing root. The proper fix, in my opinion, is to tell udev that it also needs to apply the rule to the placeholder device file. Thus, the udev-rule needs to be extended to read
```
KERNEL=="vhba_ctl", SUBSYSTEM=="misc", TAG+="uaccess", OPTIONS+="static_node=vhba_ctl"
```
